
const PortalConstants = {
  FETCH_STUDIOS: 'FETCH_STUDIOS',
  FETCHING_STUDIOS: 'FETCHING_STUDIOS',
  STUDIOS_RECEIVED: 'STUDIOS_RECEIVED',
  TOGGLE_STUDIOS: 'TOGGLE_STUDIOS',
  TOGGLE_DAYS: 'TOGGLE_DAYS'
}

export default PortalConstants;
